# Generated by Django 2.2 on 2020-03-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200311_2013'),
        ('documentos', '0004_auto_20200311_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='entidad',
        ),
        migrations.AddField(
            model_name='documento',
            name='entidad',
            field=models.ManyToManyField(null=True, to='documentos.Entidad'),
        ),
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ManyToManyField(null=True, to='usuarios.Usuario'),
        ),
    ]
