# Generated by Django 2.2 on 2020-03-12 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(blank=True, max_length=100)),
                ('representante', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('tipo', models.CharField(choices=[('1', 'Entidad Receptora'), ('2', 'Entidad Emisora')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.Entidad'),
        ),
    ]
