# Generated by Django 2.2 on 2020-03-12 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_rol'),
        ('documentos', '0002_auto_20200311_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
    ]
