# Generated by Django 2.2 on 2020-03-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_auto_20200315_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='codigo',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
