# Generated by Django 2.2 on 2020-03-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_auto_20200315_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='entidad_receptora',
        ),
        migrations.DeleteModel(
            name='EntidadReceptora',
        ),
    ]
