# Generated by Django 2.2 on 2020-03-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_auto_20200316_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='barrio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='parroquia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carreras.Carrera'),
        ),
    ]
