# Generated by Django 2.2 on 2020-03-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_auto_20200318_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
