# Generated by Django 2.2 on 2020-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_auto_20200318_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='fecha_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
