# Generated by Django 2.2 on 2020-03-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_auto_20200318_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carreras.Carrera'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='entidad_emisora',
            field=models.ManyToManyField(blank=True, null=True, to='documentos.EntidadEmisora'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ManyToManyField(blank=True, null=True, to='usuarios.Usuario'),
        ),
    ]
