# Generated by Django 2.2 on 2020-03-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='decula',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
