# Generated by Django 2.2 on 2020-03-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
